
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/07a_lsuv.ipynb

from exp.nb_07 import *

def get_batch(dl, run):
    run.xb, run.yb = next(iter(dl))
    for cb in run.cbs:
        cb.set_runner(run)
    run('begin_batch')
    return run.xb, run.yb

def find_modules(m, cond):
    if cond(m):
        return [m]
    return sum([find_modules(o,cond) for o in m.children()], [])

lin_layers = (nn.Conv1d, nn.Conv2d, nn.Conv3d, nn.Linear, nn.ReLU)

def is_lin_layer(l):
    return isinstance(l, lin_layers)

def lsuv_module(m, xb, eps=1e-3):
    '''
    m - module
    xb - The initial train batch
    '''
    h = Hook(m, append_stat)
    while mdl(xb) is not None and abs(h.mean) > eps:
        m.bias = m.bias - h.mean
    while mdl(xb) is not None and abs(h.std - 1) > eps:
        m.weight.data = m.weight.data / h.std

    h.remove()
    return h.mean, h.std